# Generated by Django 6.0.4 on 2026-05-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0002_person_score_gad7_person_score_phq9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
