# Generated by Django 6.0.4 on 2026-06-01 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0005_alter_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
    ]
