# Generated by Django 6.0.4 on 2026-06-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0007_assements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assements',
            name='score_gad7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assements',
            name='score_phq9',
            field=models.IntegerField(default=0),
        ),
    ]
