# Generated by Django 6.0.4 on 2026-06-08 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0008_alter_assements_score_gad7_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='score_gad7',
        ),
        migrations.RemoveField(
            model_name='person',
            name='score_phq9',
        ),
    ]
